name: PassStrength Workflow - Nipun Waas
run-name: ${{ github.actor }} is testing out cifuzz CI/CD 🚀
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag passcheckerimage
      - run : docker images
      - name: Run Docker Container and Get Container ID
        id: container
        run: |
          container_id=$(docker run -d passcheckerimage)
          echo "::set-output name=container_id::$container_id"
      - name: Wait for Container to Finish
        run: |
          container_id="${{ steps.container.outputs.container_id }}"
          while [ -n "$(docker ps -q --filter "id=$container_id")" ]; do
            echo "Container is still running, waiting..."
            sleep 10
          done
      - name: Copy logs from container
        run: |
          container_id="${{ steps.container.outputs.container_id }}"
          docker cp $container_id:/PasswordStrength/fuzzing.log /Downloads
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact-passchecker
          path: passchecker.txt
          retention-days: 5
